//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MvcLoggingDemo.Models.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MvcLoggingDemoContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MvcLoggingDemoContainer object using the connection string found in the 'MvcLoggingDemoContainer' section of the application configuration file.
        /// </summary>
        public MvcLoggingDemoContainer() : base("name=MvcLoggingDemoContainer", "MvcLoggingDemoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcLoggingDemoContainer object.
        /// </summary>
        public MvcLoggingDemoContainer(string connectionString) : base(connectionString, "MvcLoggingDemoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcLoggingDemoContainer object.
        /// </summary>
        public MvcLoggingDemoContainer(EntityConnection connection) : base(connection, "MvcLoggingDemoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ELMAH_Error> ELMAH_Error
        {
            get
            {
                if ((_ELMAH_Error == null))
                {
                    _ELMAH_Error = base.CreateObjectSet<ELMAH_Error>("ELMAH_Error");
                }
                return _ELMAH_Error;
            }
        }
        private ObjectSet<ELMAH_Error> _ELMAH_Error;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log4Net_Error> Log4Net_Error
        {
            get
            {
                if ((_Log4Net_Error == null))
                {
                    _Log4Net_Error = base.CreateObjectSet<Log4Net_Error>("Log4Net_Error");
                }
                return _Log4Net_Error;
            }
        }
        private ObjectSet<Log4Net_Error> _Log4Net_Error;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NLog_Error> NLog_Error
        {
            get
            {
                if ((_NLog_Error == null))
                {
                    _NLog_Error = base.CreateObjectSet<NLog_Error>("NLog_Error");
                }
                return _NLog_Error;
            }
        }
        private ObjectSet<NLog_Error> _NLog_Error;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vw_aspnet_WebEvents_extended> vw_aspnet_WebEvents_extended
        {
            get
            {
                if ((_vw_aspnet_WebEvents_extended == null))
                {
                    _vw_aspnet_WebEvents_extended = base.CreateObjectSet<vw_aspnet_WebEvents_extended>("vw_aspnet_WebEvents_extended");
                }
                return _vw_aspnet_WebEvents_extended;
            }
        }
        private ObjectSet<vw_aspnet_WebEvents_extended> _vw_aspnet_WebEvents_extended;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ELMAH_Error EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToELMAH_Error(ELMAH_Error eLMAH_Error)
        {
            base.AddObject("ELMAH_Error", eLMAH_Error);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Log4Net_Error EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLog4Net_Error(Log4Net_Error log4Net_Error)
        {
            base.AddObject("Log4Net_Error", log4Net_Error);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NLog_Error EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNLog_Error(NLog_Error nLog_Error)
        {
            base.AddObject("NLog_Error", nLog_Error);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vw_aspnet_WebEvents_extended EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovw_aspnet_WebEvents_extended(vw_aspnet_WebEvents_extended vw_aspnet_WebEvents_extended)
        {
            base.AddObject("vw_aspnet_WebEvents_extended", vw_aspnet_WebEvents_extended);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcLoggingDemoModel", Name="ELMAH_Error")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ELMAH_Error : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ELMAH_Error object.
        /// </summary>
        /// <param name="errorId">Initial value of the ErrorId property.</param>
        /// <param name="application">Initial value of the Application property.</param>
        /// <param name="host">Initial value of the Host property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="statusCode">Initial value of the StatusCode property.</param>
        /// <param name="timeUtc">Initial value of the TimeUtc property.</param>
        /// <param name="sequence">Initial value of the Sequence property.</param>
        /// <param name="allXml">Initial value of the AllXml property.</param>
        public static ELMAH_Error CreateELMAH_Error(global::System.Guid errorId, global::System.String application, global::System.String host, global::System.String type, global::System.String source, global::System.String message, global::System.String user, global::System.Int32 statusCode, global::System.DateTime timeUtc, global::System.Int32 sequence, global::System.String allXml)
        {
            ELMAH_Error eLMAH_Error = new ELMAH_Error();
            eLMAH_Error.ErrorId = errorId;
            eLMAH_Error.Application = application;
            eLMAH_Error.Host = host;
            eLMAH_Error.Type = type;
            eLMAH_Error.Source = source;
            eLMAH_Error.Message = message;
            eLMAH_Error.User = user;
            eLMAH_Error.StatusCode = statusCode;
            eLMAH_Error.TimeUtc = timeUtc;
            eLMAH_Error.Sequence = sequence;
            eLMAH_Error.AllXml = allXml;
            return eLMAH_Error;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ErrorId
        {
            get
            {
                return _ErrorId;
            }
            set
            {
                if (_ErrorId != value)
                {
                    OnErrorIdChanging(value);
                    ReportPropertyChanging("ErrorId");
                    _ErrorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ErrorId");
                    OnErrorIdChanged();
                }
            }
        }
        private global::System.Guid _ErrorId;
        partial void OnErrorIdChanging(global::System.Guid value);
        partial void OnErrorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Application
        {
            get
            {
                return _Application;
            }
            set
            {
                OnApplicationChanging(value);
                ReportPropertyChanging("Application");
                _Application = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Application");
                OnApplicationChanged();
            }
        }
        private global::System.String _Application;
        partial void OnApplicationChanging(global::System.String value);
        partial void OnApplicationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Host
        {
            get
            {
                return _Host;
            }
            set
            {
                OnHostChanging(value);
                ReportPropertyChanging("Host");
                _Host = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Host");
                OnHostChanged();
            }
        }
        private global::System.String _Host;
        partial void OnHostChanging(global::System.String value);
        partial void OnHostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusCode
        {
            get
            {
                return _StatusCode;
            }
            set
            {
                OnStatusCodeChanging(value);
                ReportPropertyChanging("StatusCode");
                _StatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCode");
                OnStatusCodeChanged();
            }
        }
        private global::System.Int32 _StatusCode;
        partial void OnStatusCodeChanging(global::System.Int32 value);
        partial void OnStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeUtc
        {
            get
            {
                return _TimeUtc;
            }
            set
            {
                OnTimeUtcChanging(value);
                ReportPropertyChanging("TimeUtc");
                _TimeUtc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeUtc");
                OnTimeUtcChanged();
            }
        }
        private global::System.DateTime _TimeUtc;
        partial void OnTimeUtcChanging(global::System.DateTime value);
        partial void OnTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Sequence
        {
            get
            {
                return _Sequence;
            }
            set
            {
                OnSequenceChanging(value);
                ReportPropertyChanging("Sequence");
                _Sequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sequence");
                OnSequenceChanged();
            }
        }
        private global::System.Int32 _Sequence;
        partial void OnSequenceChanging(global::System.Int32 value);
        partial void OnSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AllXml
        {
            get
            {
                return _AllXml;
            }
            set
            {
                OnAllXmlChanging(value);
                ReportPropertyChanging("AllXml");
                _AllXml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AllXml");
                OnAllXmlChanged();
            }
        }
        private global::System.String _AllXml;
        partial void OnAllXmlChanging(global::System.String value);
        partial void OnAllXmlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcLoggingDemoModel", Name="Log4Net_Error")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log4Net_Error : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log4Net_Error object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="thread">Initial value of the Thread property.</param>
        /// <param name="level">Initial value of the Level property.</param>
        /// <param name="logger">Initial value of the Logger property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static Log4Net_Error CreateLog4Net_Error(global::System.Int32 id, global::System.DateTime date, global::System.String thread, global::System.String level, global::System.String logger, global::System.String message)
        {
            Log4Net_Error log4Net_Error = new Log4Net_Error();
            log4Net_Error.Id = id;
            log4Net_Error.Date = date;
            log4Net_Error.Thread = thread;
            log4Net_Error.Level = level;
            log4Net_Error.Logger = logger;
            log4Net_Error.Message = message;
            return log4Net_Error;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Thread
        {
            get
            {
                return _Thread;
            }
            set
            {
                if (_Thread != value)
                {
                    OnThreadChanging(value);
                    ReportPropertyChanging("Thread");
                    _Thread = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Thread");
                    OnThreadChanged();
                }
            }
        }
        private global::System.String _Thread;
        partial void OnThreadChanging(global::System.String value);
        partial void OnThreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Level
        {
            get
            {
                return _Level;
            }
            set
            {
                if (_Level != value)
                {
                    OnLevelChanging(value);
                    ReportPropertyChanging("Level");
                    _Level = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Level");
                    OnLevelChanged();
                }
            }
        }
        private global::System.String _Level;
        partial void OnLevelChanging(global::System.String value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logger
        {
            get
            {
                return _Logger;
            }
            set
            {
                if (_Logger != value)
                {
                    OnLoggerChanging(value);
                    ReportPropertyChanging("Logger");
                    _Logger = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Logger");
                    OnLoggerChanged();
                }
            }
        }
        private global::System.String _Logger;
        partial void OnLoggerChanging(global::System.String value);
        partial void OnLoggerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                if (_Message != value)
                {
                    OnMessageChanging(value);
                    ReportPropertyChanging("Message");
                    _Message = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Message");
                    OnMessageChanged();
                }
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcLoggingDemoModel", Name="NLog_Error")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NLog_Error : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NLog_Error object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="time_stamp">Initial value of the time_stamp property.</param>
        /// <param name="host">Initial value of the host property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="source">Initial value of the source property.</param>
        /// <param name="message">Initial value of the message property.</param>
        /// <param name="level">Initial value of the level property.</param>
        /// <param name="logger">Initial value of the logger property.</param>
        /// <param name="stacktrace">Initial value of the stacktrace property.</param>
        /// <param name="allxml">Initial value of the allxml property.</param>
        public static NLog_Error CreateNLog_Error(global::System.Int32 id, global::System.DateTime time_stamp, global::System.String host, global::System.String type, global::System.String source, global::System.String message, global::System.String level, global::System.String logger, global::System.String stacktrace, global::System.String allxml)
        {
            NLog_Error nLog_Error = new NLog_Error();
            nLog_Error.Id = id;
            nLog_Error.time_stamp = time_stamp;
            nLog_Error.host = host;
            nLog_Error.type = type;
            nLog_Error.source = source;
            nLog_Error.message = message;
            nLog_Error.level = level;
            nLog_Error.logger = logger;
            nLog_Error.stacktrace = stacktrace;
            nLog_Error.allxml = allxml;
            return nLog_Error;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time_stamp
        {
            get
            {
                return _time_stamp;
            }
            set
            {
                Ontime_stampChanging(value);
                ReportPropertyChanging("time_stamp");
                _time_stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_stamp");
                Ontime_stampChanged();
            }
        }
        private global::System.DateTime _time_stamp;
        partial void Ontime_stampChanging(global::System.DateTime value);
        partial void Ontime_stampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String host
        {
            get
            {
                return _host;
            }
            set
            {
                OnhostChanging(value);
                ReportPropertyChanging("host");
                _host = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("host");
                OnhostChanged();
            }
        }
        private global::System.String _host;
        partial void OnhostChanging(global::System.String value);
        partial void OnhostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String level
        {
            get
            {
                return _level;
            }
            set
            {
                OnlevelChanging(value);
                ReportPropertyChanging("level");
                _level = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("level");
                OnlevelChanged();
            }
        }
        private global::System.String _level;
        partial void OnlevelChanging(global::System.String value);
        partial void OnlevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String logger
        {
            get
            {
                return _logger;
            }
            set
            {
                OnloggerChanging(value);
                ReportPropertyChanging("logger");
                _logger = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("logger");
                OnloggerChanged();
            }
        }
        private global::System.String _logger;
        partial void OnloggerChanging(global::System.String value);
        partial void OnloggerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String stacktrace
        {
            get
            {
                return _stacktrace;
            }
            set
            {
                OnstacktraceChanging(value);
                ReportPropertyChanging("stacktrace");
                _stacktrace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("stacktrace");
                OnstacktraceChanged();
            }
        }
        private global::System.String _stacktrace;
        partial void OnstacktraceChanging(global::System.String value);
        partial void OnstacktraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String allxml
        {
            get
            {
                return _allxml;
            }
            set
            {
                OnallxmlChanging(value);
                ReportPropertyChanging("allxml");
                _allxml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("allxml");
                OnallxmlChanged();
            }
        }
        private global::System.String _allxml;
        partial void OnallxmlChanging(global::System.String value);
        partial void OnallxmlChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcLoggingDemoModel", Name="vw_aspnet_WebEvents_extended")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_aspnet_WebEvents_extended : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vw_aspnet_WebEvents_extended object.
        /// </summary>
        /// <param name="eventId">Initial value of the EventId property.</param>
        /// <param name="eventTimeUtc">Initial value of the EventTimeUtc property.</param>
        /// <param name="eventTime">Initial value of the EventTime property.</param>
        /// <param name="eventType">Initial value of the EventType property.</param>
        /// <param name="eventSequence">Initial value of the EventSequence property.</param>
        /// <param name="eventOccurrence">Initial value of the EventOccurrence property.</param>
        /// <param name="eventCode">Initial value of the EventCode property.</param>
        /// <param name="eventDetailCode">Initial value of the EventDetailCode property.</param>
        /// <param name="machineName">Initial value of the MachineName property.</param>
        /// <param name="level">Initial value of the Level property.</param>
        public static vw_aspnet_WebEvents_extended Createvw_aspnet_WebEvents_extended(global::System.String eventId, global::System.DateTime eventTimeUtc, global::System.DateTime eventTime, global::System.String eventType, global::System.Decimal eventSequence, global::System.Decimal eventOccurrence, global::System.Int32 eventCode, global::System.Int32 eventDetailCode, global::System.String machineName, global::System.String level)
        {
            vw_aspnet_WebEvents_extended vw_aspnet_WebEvents_extended = new vw_aspnet_WebEvents_extended();
            vw_aspnet_WebEvents_extended.EventId = eventId;
            vw_aspnet_WebEvents_extended.EventTimeUtc = eventTimeUtc;
            vw_aspnet_WebEvents_extended.EventTime = eventTime;
            vw_aspnet_WebEvents_extended.EventType = eventType;
            vw_aspnet_WebEvents_extended.EventSequence = eventSequence;
            vw_aspnet_WebEvents_extended.EventOccurrence = eventOccurrence;
            vw_aspnet_WebEvents_extended.EventCode = eventCode;
            vw_aspnet_WebEvents_extended.EventDetailCode = eventDetailCode;
            vw_aspnet_WebEvents_extended.MachineName = machineName;
            vw_aspnet_WebEvents_extended.Level = level;
            return vw_aspnet_WebEvents_extended;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                if (_EventId != value)
                {
                    OnEventIdChanging(value);
                    ReportPropertyChanging("EventId");
                    _EventId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }
        private global::System.String _EventId;
        partial void OnEventIdChanging(global::System.String value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventTimeUtc
        {
            get
            {
                return _EventTimeUtc;
            }
            set
            {
                if (_EventTimeUtc != value)
                {
                    OnEventTimeUtcChanging(value);
                    ReportPropertyChanging("EventTimeUtc");
                    _EventTimeUtc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventTimeUtc");
                    OnEventTimeUtcChanged();
                }
            }
        }
        private global::System.DateTime _EventTimeUtc;
        partial void OnEventTimeUtcChanging(global::System.DateTime value);
        partial void OnEventTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventTime
        {
            get
            {
                return _EventTime;
            }
            set
            {
                if (_EventTime != value)
                {
                    OnEventTimeChanging(value);
                    ReportPropertyChanging("EventTime");
                    _EventTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventTime");
                    OnEventTimeChanged();
                }
            }
        }
        private global::System.DateTime _EventTime;
        partial void OnEventTimeChanging(global::System.DateTime value);
        partial void OnEventTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventType
        {
            get
            {
                return _EventType;
            }
            set
            {
                if (_EventType != value)
                {
                    OnEventTypeChanging(value);
                    ReportPropertyChanging("EventType");
                    _EventType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("EventType");
                    OnEventTypeChanged();
                }
            }
        }
        private global::System.String _EventType;
        partial void OnEventTypeChanging(global::System.String value);
        partial void OnEventTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EventSequence
        {
            get
            {
                return _EventSequence;
            }
            set
            {
                if (_EventSequence != value)
                {
                    OnEventSequenceChanging(value);
                    ReportPropertyChanging("EventSequence");
                    _EventSequence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventSequence");
                    OnEventSequenceChanged();
                }
            }
        }
        private global::System.Decimal _EventSequence;
        partial void OnEventSequenceChanging(global::System.Decimal value);
        partial void OnEventSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EventOccurrence
        {
            get
            {
                return _EventOccurrence;
            }
            set
            {
                if (_EventOccurrence != value)
                {
                    OnEventOccurrenceChanging(value);
                    ReportPropertyChanging("EventOccurrence");
                    _EventOccurrence = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventOccurrence");
                    OnEventOccurrenceChanged();
                }
            }
        }
        private global::System.Decimal _EventOccurrence;
        partial void OnEventOccurrenceChanging(global::System.Decimal value);
        partial void OnEventOccurrenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventCode
        {
            get
            {
                return _EventCode;
            }
            set
            {
                if (_EventCode != value)
                {
                    OnEventCodeChanging(value);
                    ReportPropertyChanging("EventCode");
                    _EventCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventCode");
                    OnEventCodeChanged();
                }
            }
        }
        private global::System.Int32 _EventCode;
        partial void OnEventCodeChanging(global::System.Int32 value);
        partial void OnEventCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventDetailCode
        {
            get
            {
                return _EventDetailCode;
            }
            set
            {
                if (_EventDetailCode != value)
                {
                    OnEventDetailCodeChanging(value);
                    ReportPropertyChanging("EventDetailCode");
                    _EventDetailCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventDetailCode");
                    OnEventDetailCodeChanged();
                }
            }
        }
        private global::System.Int32 _EventDetailCode;
        partial void OnEventDetailCodeChanging(global::System.Int32 value);
        partial void OnEventDetailCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApplicationPath
        {
            get
            {
                return _ApplicationPath;
            }
            set
            {
                OnApplicationPathChanging(value);
                ReportPropertyChanging("ApplicationPath");
                _ApplicationPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApplicationPath");
                OnApplicationPathChanged();
            }
        }
        private global::System.String _ApplicationPath;
        partial void OnApplicationPathChanging(global::System.String value);
        partial void OnApplicationPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApplicationVirtualPath
        {
            get
            {
                return _ApplicationVirtualPath;
            }
            set
            {
                OnApplicationVirtualPathChanging(value);
                ReportPropertyChanging("ApplicationVirtualPath");
                _ApplicationVirtualPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApplicationVirtualPath");
                OnApplicationVirtualPathChanged();
            }
        }
        private global::System.String _ApplicationVirtualPath;
        partial void OnApplicationVirtualPathChanging(global::System.String value);
        partial void OnApplicationVirtualPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                if (_MachineName != value)
                {
                    OnMachineNameChanging(value);
                    ReportPropertyChanging("MachineName");
                    _MachineName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MachineName");
                    OnMachineNameChanged();
                }
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RequestUrl
        {
            get
            {
                return _RequestUrl;
            }
            set
            {
                OnRequestUrlChanging(value);
                ReportPropertyChanging("RequestUrl");
                _RequestUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RequestUrl");
                OnRequestUrlChanged();
            }
        }
        private global::System.String _RequestUrl;
        partial void OnRequestUrlChanging(global::System.String value);
        partial void OnRequestUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExceptionType
        {
            get
            {
                return _ExceptionType;
            }
            set
            {
                OnExceptionTypeChanging(value);
                ReportPropertyChanging("ExceptionType");
                _ExceptionType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExceptionType");
                OnExceptionTypeChanged();
            }
        }
        private global::System.String _ExceptionType;
        partial void OnExceptionTypeChanging(global::System.String value);
        partial void OnExceptionTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details;
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Level
        {
            get
            {
                return _Level;
            }
            set
            {
                if (_Level != value)
                {
                    OnLevelChanging(value);
                    ReportPropertyChanging("Level");
                    _Level = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Level");
                    OnLevelChanged();
                }
            }
        }
        private global::System.String _Level;
        partial void OnLevelChanging(global::System.String value);
        partial void OnLevelChanged();

        #endregion

    
    }

    #endregion

    
}
